#!/usr/bin/env bash
# Installs HAProxy with the following configurations:
# - Enables management via the init script.
# - Distributes requests using a round-robin algorithm.

sudo apt-get install -y haproxy

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

cat <<EOT | sudo tee -a /etc/haproxy/haproxy.cfg
frontend cosmasnnabuike.tech
    timeout client  30000
    bind 0:80
    default_backend cosmasnnabuike.tech_backend

backend cosmasnnabuike.tech_backend
    timeout connect  3000
    timeout server  30000
    balance roundrobin
    server 218560-web-01 100.26.168.46 check
    server 218560-web-02 3.83.227.213 check
EOT

sudo service haproxy restart
